name: 'Checkout'
description: 'Checkout a repository'
inputs:
  repository:
    description: 'Repository to checkout'
    required: true
    default: ${{ github.repository }}
  ref:
    description: 'The branch, tag or SHA to checkout'
    required: false
    default: 'main'
runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}