name: "Checkout"
description: "Checkout a repository"
inputs:
  ref:
    description: "The branch, tag or SHA to checkout"
    required: false
    default: "main"
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: ${{ inputs.ref }}
