name: "GitHub Release"
description: "Create a GitHub release"
inputs:
  tag_name:
    description: "The name of the tag for the release"
    required: true
  files:
    description: "Files to upload to the release"
    required: true
runs:
  using: "composite"
  steps:
    - name: Create GitHub release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ inputs.tag_name }}
        files: ${{ inputs.files }}
