name: C/C++ Code Compilation and Release

on:
  push:
    branches:
      - main # or any branch you want to track

jobs:
  compile:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    continue-on-error: true # Allow other jobs to continue even if this one fails
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up C++ build environment
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            echo "Installing MinGW for Windows..."
            choco install mingw --version latest -y
            # Check g++ version
            g++ --version || echo "g++ is not installed properly on Windows."
          elif [ "$RUNNER_OS" == "macOS" ]; then
            echo "Installing latest g++ on macOS using Homebrew..."
            brew update
            brew install gcc
          elif [ "$RUNNER_OS" == "Linux" ]; then
            echo "Installing latest g++ on Linux..."
            sudo apt update
            sudo apt install -y g++
          fi

      - name: Compile C/C++ code
        run: |
          mkdir -p build
          # Find all .cpp files recursively and compile them
          find . -type f -name "*.cpp" | while read file; do
            if [ -f "$file" ]; then
              # Check if the file contains a main function
              if grep -q "int main" "$file"; then
                # Extract the filename without the path
                filename=$(basename "$file" .cpp)

                # Compile the C/C++ files based on OS
                if [ "$RUNNER_OS" == "Windows" ]; then
                  echo "Compiling for Windows using g++..."
                  g++ "$file" -o build/"$filename".exe || echo "Error compiling $file on $RUNNER_OS. Skipping."
                elif [ "$RUNNER_OS" == "macOS" ] || [ "$RUNNER_OS" == "Linux" ]; then
                  echo "Compiling for $RUNNER_OS using g++..."
                  g++ "$file" -o build/"$filename" || echo "Error compiling $file on $RUNNER_OS. Skipping."
                fi
              else
                echo "Skipping $file: No main function found."
              fi
            else
              echo "Skipping $file: File does not exist."
            fi
          done

      - name: Zip individual OS compiled files
        run: |
          mkdir release
          if [ "$RUNNER_OS" == "Windows" ]; then
            # Only zip if the executable exists
            if [ -f build/*.exe ]; then
              zip -r release/windows_code.zip build/*.exe
            else
              echo "No executable found for Windows. Skipping zip creation."
            fi
          elif [ "$RUNNER_OS" == "macOS" ]; then
            # Only zip if files exist
            if [ -f build/* ]; then
              zip -r release/macos_code.zip build/*
            else
              echo "No files found for macOS. Skipping zip creation."
            fi
          elif [ "$RUNNER_OS" == "Linux" ]; then
            # Only zip if files exist
            if [ -f build/* ]; then
              zip -r release/linux_code.zip build/*
            else
              echo "No files found for Linux. Skipping zip creation."
            fi
          fi

  create_combined_zip:
    needs: compile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Combine all OS releases into one zip and tar file
        run: |
          mkdir combined
          # Check if each zip exists before copying
          if [ -f release/windows_code.zip ]; then
            cp release/windows_code.zip combined/
          else
            echo "No Windows zip file found. Skipping."
          fi

          if [ -f release/macos_code.zip ]; then
            cp release/macos_code.zip combined/
          else
            echo "No macOS zip file found. Skipping."
          fi

          if [ -f release/linux_code.zip ]; then
            cp release/linux_code.zip combined/
          else
            echo "No Linux zip file found. Skipping."
          fi

          # Create combined zip and tar only if there are files to combine
          if [ "$(ls -A combined)" ]; then
            zip -r combined/combined_code.zip combined/
            tar -cvf combined/combined_code.tar combined/
          else
            echo "No files to combine. Skipping zip and tar creation."
          fi

  release:
    needs: create_combined_zip
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate a tag based on the current commit
        id: generate_tag
        run: |
          tag="release-$(date +'%Y%m%d%H%M%S')-${GITHUB_SHA}"
          echo "Generated tag: $tag"
          echo "::set-output name=tag::$tag"

      - name: Create a Git tag
        run: |
          git tag ${{ steps.generate_tag.outputs.tag }}
          git push origin ${{ steps.generate_tag.outputs.tag }}

      - name: Upload individual OS zip files
        uses: softprops/action-gh-release@v1
        with:
          tag: ${{ steps.generate_tag.outputs.tag }}
          files: release/windows_code.zip,release/macos_code.zip,release/linux_code.zip

      - name: Upload combined zip and tar files
        uses: softprops/action-gh-release@v1
        with:
          tag: ${{ steps.generate_tag.outputs.tag }}
          files: combined/combined_code.zip,combined/combined_code.tar
